assets:
  settings.xml: gap-enterprise/home#assets/settings.xml
  public.key: gap-enterprise/home#assets/public.key
  private.key: gap-enterprise/home#assets/private.key
  id_rsa_surati_vps: gap-enterprise/home#assets/id_rsa_surati_vps
  id_rsa_surati_vps.pub: gap-enterprise/home#assets/id_rsa_surati_vps.pub
  surati_vps_ssh_config: gap-enterprise/home#assets/surati_vps_ssh_config
architect:
  - baudoliver7
install: |
  javac -version
release:
    script: |-
     [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
     gpg --import /home/r/public.key
     gpg --allow-secret-key-import --import --batch --pinentry-mode=loopback /home/r/private.key 
     mvn versions:set "-DnewVersion=${tag}"
     git commit -am "${tag}"
     mvn clean install -Dinvoker.skip
     mvn clean deploy -Psonatype,surati --errors --settings /home/r/settings.xml -Dstyle.color=never
deploy:
  script: |-
    mkdir ~/.ssh
    mv ~/id_rsa_surati_vps ~/id_rsa_surati_vps.pub ~/.ssh/
    chmod -R 600 ~/.ssh/*
    mv ~/surati_vps_ssh_config ~/.ssh/config
    ssh surati_vps "rm -rf gap"
    scp -C -r ~/repo surati_vps:~/gap
    ssh surati_vps "cd gap && sh deploy.sh -p 7070"
